#!/usr/bin/env bash
# Installs and configures nginx, changes the listening port to 80
# and changes the nginx landing page.

sudo apt install nginx -y
sudo sed -i "s/.*/Hello World!/" /var/www/html/index.nginx-debian.html
sudo service nginx start
