#!/usr/bin/env bash
# Configures the location /redirect_me to point to another url
sudo sed -i "s/# as directory, then fall back to displaying a 404./rewrite ^\/redirect_me\(\.\\*\)\$ https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
sudo service nginx reload
