#!/usr/bin/env bash
#this will install and configer nginx on new machine
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "s/\# SSL configuration/\# SSL configuration \n\tadd_header X-Served-By '\$HOSTNAME';/" /etc/nginx/sites-available/default
sudo service nginx reload

