#!/usr/bin/env bash
# Block all other traffic 
sudo apt -y update
sudo apt-get install ufw -y
sudo ufw default deny incoming
ufw default allow outgoing
sudo ufw allow ssh
ufw enable
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable
sudo ufw reload
